spring.application.name="Task Manager"
# Database configuration
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${DATASOURCE_URL}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=create-only
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect